name: dart_playground
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: nerve2009 <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  intl_translation: ^0.17.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
